# Form implementation generated from reading ui file 'c:\Users\24Dan\OneDrive - Moreton Bay Colleges\Year 12\Digital Solutions\IA2\Code file\myourapi\ApiDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApiDialog(object):
    def setupUi(self, ApiDialog):
        ApiDialog.setObjectName("ApiDialog")
        ApiDialog.resize(415, 299)
        self.verticalLayout = QtWidgets.QVBoxLayout(ApiDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.apiTree = QtWidgets.QTreeWidget(parent=ApiDialog)
        self.apiTree.setObjectName("apiTree")
        self.apiTree.headerItem().setText(0, "1")
        self.apiTree.header().setVisible(False)
        self.verticalLayout.addWidget(self.apiTree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(parent=ApiDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ApiDialog)
        QtCore.QMetaObject.connectSlotsByName(ApiDialog)

    def retranslateUi(self, ApiDialog):
        _translate = QtCore.QCoreApplication.translate
        ApiDialog.setWindowTitle(_translate("ApiDialog", "Dialog"))
        self.closeButton.setText(_translate("ApiDialog", "Close"))
